[package]
name = "tests-mock-s3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "S3 / minIO mock backend (5 behaviors)"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tests-mock-core = { workspace = true }
